### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by fufflu** [kemo14331/Particle-Converter#2]
**I upload the image and this is happening**
![image](https://user-images.githubusercontent.com/65746909/106520497-eeb81400-64ed-11eb-8272-1f7242b08e1a.png)

**Comment by kemo14331** [comment]
Thank you for the bug report.
The problem may have been fixed in version 1.0.3.
Please check it out.

**Comment by Androkai** [comment]
I get the same message in 1.0.3 until I add the x64 runtime dependencies for my system from 1.0.2 to the main directory of 1.0.3. Here's the exception log with dependencies missing:
```
System.Collections.ListDictionaryInternal
System.TypeInitializationException: The type initializer for 'OpenCvSharp.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'OpenCvSharpExtern' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at OpenCvSharp.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
   at OpenCvSharp.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
   at OpenCvSharp.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at OpenCvSharp.NativeMethods.imgcodecs_imread(String fileName, Int32 flags, IntPtr& returnValue)
   at OpenCvSharp.Mat..ctor(String fileName, ImreadModes flags)
   at ParticleConverter.util.ImageConverter.Load(String imagePath)
   at ParticleConverter.MainWindow.ImageFileLoad()
```

**Comment by kemo14331** [comment]
Thank you.
I have fixed it.
Please download the updated binary of the same release.

**Comment by namelesss1185** [comment]
i have the problem when i install version 1.0.4
failed tp load image
